# Generated by Django 4.2.7 on 2024-01-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='book-icon.png', upload_to='profile_images'),
        ),
    ]
