# Generated by Django 4.2.7 on 2024-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='static/images/book-icon.png', upload_to='profile_images'),
        ),
    ]
